name: flaskr                                                                                      
channels:                                                                                         
  - conda-forge                                                                                   
  - defaults                                                                                      
dependencies:                                                                                     
  - conda-forge::nodejs                                                                           
  - make                                                                                          
  - r-base                                                                                        
  - r-essentials   